[package]
name = "gl-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = "1.0"
tracing = { version = "^0.1", features = ["std"] }
serde_yaml.workspace = true
